AllCops:
  TargetRubyVersion: 3.3
  NewCops: enable

Style/Documentation:
  Enabled: false

Metrics/MethodLength:
  Max: 25

Metrics/ClassLength:
  Max: 150

Metrics/AbcSize:
  Max: 22

Metrics/CyclomaticComplexity:
  Max: 9

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes
